# DO NOT EDIT THIS FILE
{ config, lib, modulesPath, ... }: {
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
	boot.kernelModules = [ "kvm-intel" "wl" ];
	boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/e816bf7c-0d8a-4a22-912b-0cee6f4c7ff0";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/67E3-17ED";
		fsType = "vfat";
		options = [ "fmask=0022" "dmask=0022" ];
	};

	swapDevices = [ { device = "/dev/disk/by-uuid/cb46259b-0bce-4cac-8056-090c98421352"; } ];

	networking.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
